# Generated by Django 3.2.13 on 2022-12-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multipage_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lorem',
            fields=[
                ('multipagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multipage_form.multipagemodel')),
                ('text_field', models.CharField(blank=True, max_length=20)),
                ('date_field', models.DateField(blank=True)),
                ('time_field', models.TimeField(blank=True)),
                ('textarea_field', models.TextField(blank=True)),
                ('select_field', models.CharField(choices=[('A', '(A) Lorem ipsum'), ('B', '(B) Dolor sit')], default='A', help_text='Lorem ipsum dolor sit amet...', max_length=1)),
                ('checkbox_field', models.BooleanField(default=False)),
                ('radio_field', models.BooleanField(default=False)),
            ],
            bases=('multipage_form.multipagemodel',),
        ),
    ]
