# Generated by Django 3.2.13 on 2022-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorem',
            name='radio2_field',
            field=models.BooleanField(default=False),
        ),
    ]
