# Generated by Django 3.2.13 on 2022-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorem', '0002_lorem_radio2_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorem',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lorem',
            name='time_field',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
